name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Start API
        run: |
          cd api
          npm install || true
          nohup node app.js &
          sleep 5

      - name: Start Web
        run: |
          cd web
          npm install || true
          nohup node app.py &
          sleep 5

      - name: Install Cypress
        run: npm install cypress --save-dev

      - name: Run Cypress tests
        run: npx cypress run

      - name: Install K6
        run: |
          sudo apt-get update
          sudo apt-get install -y gnupg2
          curl -s https://packagecloud.io/install/repositories/loadimpact/k6/script.deb.sh | sudo bash
          sudo apt-get install k6

      - name: Run K6 tests
        run: k6 run tests/performance/*.js
