name: 'Controle Financeiro App - CI'

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      API_URL: http://localhost:3000
      WEB_URL: http://localhost:4000

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Start API
        run: |
          cd api
          npm install || true
          nohup node app.js &
          sleep 5

      - name: Start Web
        run: |
          cd web
          npm install || true
          nohup node server.js &
          sleep 5

      - name: Run Cypress tests
        run: |
          cd tests/functional
          npm install || true
          npx cypress run

      - name: Setup k6
        uses: grafana/setup-k6-action@v1 # Install k6

      - name: Run k6 tests
        uses: grafana/run-k6-action@v1 # Execute k6 tests
        with:
          path: |
            ./tests/performance/ct01-login.test.js
            ./tests/performance/ct02-lancamentos.test.js
            ./tests/performance/ct03-listagem.test.js
            ./tests/performance/ct04-totalizador.test.js
            ./tests/performance/ct05-estabilidade.test.js